package com.birdclinic.BirdClinic.models.home;

// import java.util.UUID;
// import org.springframework.stereotype.Component;

public class HomePageDTOImpl implements HomePageDTO {
    private int homePageID;
    private String homePageHeader;
    private String homePageContent;

    // private static class IllegalContentException extends Exception {
    //     IllegalContentException() {
    //         super("The content is illegal or unsafe.");
    //     }
    // }

    // private static class RepeatHeaderException extends Exception {
    //     RepeatHeaderException() {
    //         super("The header already exists.");
    //     }
    // }

    public HomePageDTOImpl() {
    }

    public HomePageDTOImpl(int id, String content, String header) {
        homePageID = id;
        homePageContent = content;
        homePageHeader = header;
    }

    //get homepage to display

    @Override
    public int gethomePageID() {
        return homePageID;
    }

    @Override
    public String gethomePageContent() {
        return homePageContent;
    }

    @Override
    public String gethomePageHeader() {
        return homePageHeader;
    }

    //for DAO

    @Override
    public void setHomePageID(int homePageID) {
        this.homePageID = homePageID;
    }

    @Override
    public void setHomePageHeader(String homePageHeader) {
        this.homePageHeader = homePageHeader;
    }

    @Override
    public void setHomePageContent(String homePageContent) {
        this.homePageContent = homePageContent;
    }

    //for admin to set a new homepage w/o having to access the actual db (id is autogenerated)

    // @Override
    // public int generatehomePage(String newContentString, String newHeaderString) {
    //     int noAttributesAffected = 0;

    //     try {
    //         createhomePageContent(newContentString);
    //         noAttributesAffected++;
    //         createhomePageHeader(newHeaderString);
    //         noAttributesAffected++;
    //     }
    //     catch (IllegalContentException | RepeatHeaderException ex) {
    //         ex.printStackTrace();
    //     }

    //     return noAttributesAffected;
    // }

    
    // private void createhomePageContent(String newContentString) throws IllegalContentException {
    //     boolean contentValidated = true;
        
    //     // validate content, set false if it's unsafe
        
    //     if (!contentValidated) throw new IllegalContentException();

    //     homePageContent = newContentString;
    // }

    

    // private void createhomePageHeader(String newHeaderString) throws RepeatHeaderException {
    //     boolean headerValidated = true;

    //     // validate header, set false if it repeats

    //     if (!headerValidated) throw new RepeatHeaderException();

    //     homePageHeader = newHeaderString;
    // }
}
